### ISSUE TITLE
Downloads fail in both Chrome and Firefox

### ISSUE THREAD

**Issue by TheRealBenForce** [Mips96/EzRO-gui#12]
Chrome and firefox are reporting that v1.2.1 is a dangerous file and blocks the download. v1.2 downloads successfully.

**Comment by TheRealBenForce** [comment]
Looks like windows defender doesn't like v1.2. I plan to load these in a sandbox in the next few days and look into them.

**Comment by Mode8fx** [comment]
One of the libraries I was using was found to have a security issue, so that may have been the problem. I compiled a new release using updated libraries and still got a warning from Defender, then recompiled and no longer get an error, so I guess it's working now?

Either way, the libraries needed to be updated anyway, so try the newest release.

**Comment by TheRealBenForce** [comment]
@Mode8fx thanks! Chrome warned me but didn't block the download. Firefox and defender had no problems.
