### ISSUE TITLE
(Aftermarket)(Homebrew)

### ISSUE THREAD

**Issue by wsamples01** [Mips96/EzRO-gui#3]
Is there a file that can be modified to categorize files with (Aftermarket) or (Homebrew) in the filename as [Unlicensed] ? These are very common in NoIntro sets. 

(Program) is another common filename, it would be nice if files with (Program) were organized into their own subfolder similar to [Unlicensed].

**Comment by Mode8fx** [comment]
I wouldn't want to put Aftermarket in Unlicensed since that's not always the case (for example, the new NES games added to the official Namco Museum Archives collections are listed as Aftermarket).

As for Program, I thought it was already there but it's not; the "Misc. Program" category covers Test Program, SDK Build, Production Test Program, Enhancement Chip, and Test Cart, but not Program. Instead of adding that to the category, I'll look into using a separate file that lets you define your own categories in case there are others I missed, and update this issue when it's done.

**Comment by Mode8fx** [comment]
I just released an update that, among other things, lets you edit the categories or add your own via SpecialCategories.py. You can add your own keywords/phrases, make a category exclusive to certain systems, and change the order of priority in the event that a rom falls under multiple categories; for example, an unlicensed compilation could go under either `NES/[Unlicensed]/[Compilations]/rom.nes` or `NES/[Compilations]/[Unlicensed]/rom.nes`.

It should hopefully be self-explanatory, but I also included a guide just in case.
