### ISSUE TITLE
NES - Region Folders

### ISSUE THREAD

**Issue by lyden27** [Mips96/EzRO-gui#7]
When selecting "Do Not Create Folder For Primary Region", my rather than moving Europe roms to their own folder like the program states it will, they are kept in the root directory with the primary region. Same for World roms. The way I have found to fix this is to select World and Europe as Secondary regions. I'm not sure if this is working as intended or not, but the description of "Do Not Create Folder For Primary Region" makes it sound like it will only keep roms from my top region in the root.

**Comment by Mode8fx** [comment]
Reworked in v1.21.

This wasn't exactly a bug, but I understand the confusion. First off, the description was outdated and indicated that only the highest priority region would be placed in root, when it's actually any primary region. Second, roms were sorted by _game_, not by _rom_. So for example, if you have Europe as a primary region, and a particular game has both Europe and USA versions, then both would be exported to root since a Europe version exists, and that takes priority over everything else. This is fine if you have `Create Game Folder for Each Game` enabled (which I would personally recommend, but that's just me), but it can look odd when you don't have that enabled.

Now, if `Create Game Folder for Each Game` is enabled, then the original behavior is used: the game folder will be placed in a particular region and/or letter folder (depending on those settings) according to whichever rom has the highest priority region. But if `Create Game Folder for Each Game` is not enabled, then each rom will now be organized individually as you had initially expected.
